title: Digital Station
author: chenXin
email: 
theme: minima
permalink: none
auto: true
gems:
  - jekyll-sitemap  #生成sitemap
  - jekyll-mentions  #允许"@ somebody"
  - jemoji  #允许标签
description: > # this means to ignore newlines until "baseurl:"
  A station for A digital players!

# social links
twitter_username:  # DO NOT include the @ character, or else the build will fail!
github_username:   # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
